/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:46085499-5dad-4fbc-b5b4-aaceac8e052a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bbxIeQxvN",
    "aws_user_pools_web_client_id": "20phan7t7jh0u0gsmlc4tiuorn",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifystorages3161648-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "amplifyapp-20220224175848-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplifyapp-20220224175848-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
    "API": {
        "endpoints": [
            {
                "name": "DataplaneAPI",
                "endpoint": "https://4l6m8j6vdc.execute-api.us-east-1.amazonaws.com"
            },
            {
                "name": "ControlPlaneAPI",
                "endpoint": "https://8cvmtacjji.execute-api.us-east-1.amazonaws.com"
            }

        
        ]
    }
};


export default awsmobile;
